export class RefCareAndSupport {
    constructor(
      public abuseNeglectedSw: string,
      public adultProtectServSw: string,
      public anotherCareGiverSw: string,
      public antrPlaceSw: string,
      public age: number,
      public behaNoneSw: string,
      public behaServicesSw: string,
      public careGiverBirthDt,
      public careGiverDiedSw: string,
      public careGiverName: string,
      public careGiverRelCd: string,
      public childProtectServSw: string,
      public cleaningDressSw: string,
      public toiletingSw: string,
      public criminalJustSw: string,
      public eatingSw: string,
      public goodDecisionsSafeSw: string,
      public knowFamilySw: string,
      public medicinesSw: string,
      public mentalHlthCrisisSw: string,
      public noneOfAboveSw: string,
      public personHelpNoneSw: string,
      public physHurtBehaSw: string,
      public primCaregiverSw: string,
      public primCrgiverDisableSw: string,
      public primCrgvrPoorHlthSw: string,
      public psychHospSw: string,
      public resTreatProgSw: string,
      public tellingOthersSw: string,
      public personId: string,
      public trnsfrBdChairToilSw: string,
      public underSimpleInstSw: string,
      public walkWheelchairSw: string,
      public reqPageId: string,
      public refId: string,
    ) { }
}
